spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.lprakapovich.blog.publicationservice.postgres.ApplicationPostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/publication_service
    username: lprakapovich
    password: lprakapovich
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: lprakapovich-group

server:
  port: 9094
