spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
              - PUT
              - DELETE
              - GET
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

