spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.lprakapovich.blog.publicationservice.postgres.ApplicationPostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/blogging_service
    username: lprakapovich
    password: lprakapovich

server:
  port: 9094

